### ISSUE TITLE
Can't reproduce working 

### ISSUE THREAD

**Issue by hacKarim** [GUNNERSx/Dell-Precision5520-hackintosh#1]
Hi, thanks for sharing your config.

I have the same laptop model. Tried with your config but I'm stuck at boot: EXITBS:START...

Is there any special config for the bios to make it past that error?

**Comment by GUNNERSx** [comment]
Take a look [here](https://www.tonymacx86.com/threads/guide-dell-xps-9560-big-sur-opencore.307163/) for the post-installation on this laptop.
And  _AppleXcpmCfgLock_ must be enabled if CFG-Lock isn't disabled in your BIOS
The [dortania guide](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html#kernel) is a must to make it work many of the pre-made EFI will not work out of the box you have to make some tweaks to config.plist

**Comment by hacKarim** [comment]
Thanks for the reply, I've had some advancement since my last comment, so I guess I need to tweak more my BIOS settings and be more patient.
Have a nice day 👍
